#intended for local development only
version: "2.1"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - lively_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "lively"
      POSTGRES_USER: "lively_db"
      POSTGRES_PASSWORD: "ac08912lkdx01sd"
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    image: redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
  storage:
    image: "minio/minio"
    restart: always
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      MINIO_ACCESS_KEY: LIVELYMINIO
      MINIO_SECRET_KEY: livelyMinioTemporarySecretKey
    volumes:
      - lively_storage:/data
    command: "server /data"
  pgweb:
    restart: always
    image: sosedoff/pgweb
    ports:
      - "127.0.0.1:8081:8081"
    links:
      - db:da
    environment:
      - DATABASE_URL=postgres://lively_db:ac08912lkdx01sd@db:5432/postgres?sslmode=disable
    depends_on:
      - db
volumes:
  lively_db:
  lively_storage:
