version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6
jobs:
  code_checking:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn run typecheck
  docker_web:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: |
          cd www && docker build -t dieff/lively_web:$CIRCLE_SHA1 .
          docker run dieff/lively_web:$CIRCLE_SHA1 -- cd www && yarn run typecheck
      - run: docker push dieff/lively_web:$CIRCLE_SHA1
workflows:
  version: 2
  master:
    jobs:
      - code_checking
      - docker_web
