version: 2.1
jobs:
  code_checking:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn run typecheck
  docker_web:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          cd www && docker build -t web .
          export WEB_TAG=$(echo $CIRCLE_SHA1 | cut -c 1-12)
          docker tag web dieff07/lively_web:latest
          docker tag web dieff07/lively_web:$WEB_TAG
          docker push dieff07/lively_web
  docker_api:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          cd api && docker build -t api .
          export API_TAG=$(echo $CIRCLE_SHA1 | cut -c 1-12)
          docker tag api dieff07/lively_api:latest
          docker tag api dieff07/lively_api:$API_TAG
          docker push dieff07/lively_api
  deploy:
    docker:
      - image: bitnami/kubectl:latest
    steps:
      - deploy:
          name: "kube deploy"
          working_directory: "/tmp"
          command: |
            echo $KUBE_CONFIG_DATA >> kube.yaml
            export API_IMAGE=dieff07/lively_api:$(echo $CIRCLE_SHA1 | cut -c 1-12)
            export WEB_IMAGE=dieff07/lively_web:$(echo $CIRCLE_SHA1 | cut -c 1-12)
            kubectl --kubeconfig kube.yaml set image deployments/web-node-deployment web=$WEB_IMAGE
            kubectl --kubeconfig kube.yaml set image deployments/api-node-deployment api=$API_IMAGE
workflows:
  version: 2
  master:
    jobs:
      - code_checking
      - docker_web:
          requires:
            - code_checking
          filters:
            branches:
              only:
                - master
      - docker_api:
          requires:
            - code_checking
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - docker_web
            - docker_api
          filters:
            branches:
              only:
                - master
