version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6
jobs:
  code_checking:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn run typecheck
  docker_web:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          cd www && docker build -t dieff/lively_web:$CIRCLE_SHA1 .
          docker push dieff/lively_web:$CIRCLE_SHA1
  docker_api:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          cd api && docker build -t dieff/lively_api:$CIRCLE_SHA1 .
          docker push dieff/lively_api:$CIRCLE_SHA1
workflows:
  version: 2
  master:
    jobs:
      - code_checking
      - docker_web:
          requires:
            - code_checking
      - docker_api:
          requires:
            - code_checking
