version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.6
jobs:
  code_checking:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn run typecheck
workflows:
  version: 2
  master:
    jobs:
      - code_checking
  build_and_publish_docker_image:
    jobs:
      - docker-publish/publish:
          path: "www"
          image: "dieff/lively_web"
      - docker-publish/publish:
          path: "api"
          image: "dieff/lively_api"
