declare namespace NodeJS {
  interface Process {
    /**
     * The value will be `true` if we are running on the client side,
     * `false` if server rendering.
     *
     * Value is generated by Webpack, and is not actually in Node or the browser.
     */
    browser: boolean;
  }
  interface Global {
    fetch: any;
  }
}
